const data = {
  _id: '6305850e45b69b1a7abf6c37',
  name: 'Daniel',
  email: 'daniel.adams1993@outlook.com',
  scores: {
    database: {
      MySQL: 0,
      MariaDB: 5,
      MSSQLSever: 0,
      MongoDB: 0,
      ElasticSearch: 0,
      redis: 0,
    },
    languages: {
      Python: 5,
      C: 0,
      Java: 0,
      'C++': 0,
      'C#': 0,
      'Visual Basic': 0,
      JavaScript: 5,
      SQL: 0,
      'Assembly language': 0,
      Swift: 0,
      'Classic Visual Basic': 0,
      'Delphi/Object Pascal': 0,
      PHP: 0,
      'Objective-C': 0,
      Go: 0,
      R: 0,
      Perl: 0,
      Lua: 0,
      Ruby: 0,
      Prolog: 0,
    },
    'cloud services': {
      AWS: 0,
      FireBase: 0,
      Azure: 0,
    },
    'Operating Systems': {
      Linux: 0,
      Windows: 0,
      iOS: 0,
      Android: 0,
    },
    Datahub: {
      'Informed Portfolio': 0,
      IILClaims: 0,
      paramters: 0,
      BBJE: 0,
    },
    'Project Management Tools': {
      Jira: 1,
      ClickUp: 0,
      Binfire: 4,
      Basecamp: 0,
      'Pivitol Tracker': 0,
      Asana: 5,
      Shortcut: 0,
      Trello: 5,
      ProofHub: 1,
      Kanbanize: 0,
      Notion: 1,
      Wrike: 1,
      Bitrix24: 1,
    },
    'Front-end Frameworks': {
      vuejs: 0,
      react: 0,
      angular: 0,
    },
    'CSS Frameworks': {
      Bootstrap: 0,
      Bulma: 0,
      'pure css': 0,
      Tailwind: 0,
    },
    'Javascript Runtime Environments': {
      Node: 0,
      Deno: 0,
      Bun: 0,
    },
  },
};

export default data;